### PR TITLE
Hotfix for nim2

### PR DESCRIPTION
**Pull request by inv2004**

### CODE REVIEW

**Comment by disruptek** [comment]
Can you explain what changed?  I don't follow Nim anymore...

**Comment by inv2004** [comment]
@disruptek I am not sure - maybe nim2 bug

**Comment by inv2004** [comment]
https://github.com/nim-lang/Nim/issues/22631

**Comment by disruptek** [comment]
Closing in favor of #6; thanks for raising the issue.

**Comment by inv2004** [comment]
this fix was better

**Pull request closed without merging**
